POST http://127.0.0.1:3000/api/user/sign-up
Content-Type: application/json

{
  "email": "adan@grr.la",
  "password": "super_duper_secret_password"
}

###

POST http://127.0.0.1:3000/api/user/sign-in
Content-Type: application/json

{
  "email": "adan@grr.la",
  "password": "super_duper_secret_password"
}

###
POST http://127.0.0.1:3000/api/operator/add
Content-Type: application/json

{
  "Name": "Operator 1",
  "NumberPhone": "3196569455"
}

###
POST http://127.0.0.1:3000/api/quotes/create
Content-Type: application/json

{
  "Name": "Adan Eva",
  "Email": "adan@grr.la",
  "NumberPhone": "(319) 656 95-48",
  "Address": "Street 7 Number 122 - 20",
  "Observation": "",
  "Value": 120000,
  "Plan": "MONTHLY"
}

###
POST http://127.0.0.1:3000/api/user/documents/obligatory
Content-Type: application/json

{
  "Process": "{{ProcessId}}",
  "Documents": [{
    "Type": "RUT",
    "MIME": "pdf",
    "Base64": "{{FileDummyPDF}}"
  }, {
    "Type": "Identification",
    "MIME": "pdf",
    "Base64": "{{FileDummyPDF}}"
  },  {
    "Type": "Certificate",
    "MIME": "pdf",
    "Base64": "{{FileDummyPDF}}"
  }]
}

###
POST http://127.0.0.1:3000/api/operator/review/documents/pending
Content-Type: application/json

{}

###
POST http://127.0.0.1:3000/api/operator/review/documents/approve
Content-Type: application/json

{
  "Process": "{{ProcessId}}"
}

###
POST http://127.0.0.1:3000/api/operator/review/documents/reject
Content-Type: application/json

{
  "Process": "{{ProcessId}}"
}

###
POST http://127.0.0.1:3000/api/operator/pay/accept
Content-Type: application/json

{
  "Process": "{{ProcessId}}"
}

###
POST http://127.0.0.1:3000/api/operator/services/view/unschedule
Content-Type: application/json

{}

### TODO: Make Test for this, only left for test
POST http://127.0.0.1:3000/api/operator/services/schedule
Content-Type: application/json

{
  "Service": "{{ProcessId}}",
  "At": "2023-10-14",
  "Operator": "Any",
  "Manifest": "Any"
}